Study autoloaded
biocore/qiita pull request #3046
Opened 2020-11-11 18:05 UTC by antgonza

Changes to support a study flag to mark as automatically loaded. In general, it should always be false, once we support autoloading we will use this flag.

2020-11-12 19:10 UTC, adswafford approved these changes
Not familiar with the code for Qiita, but from what I can tell it looks like everything is set as expected for adding the autoloaded flag for setting and getting later.

2020-11-17 01:34 UTC, ElDeveloper requested changes
Just a few small changes. Quick question, is this attribute going to be visible as a metadata column?

2020-11-17 01:34 UTC, ElDeveloper commented on qiita_db/study.py
> +            If the study was loaded or not
```suggestion
            If the study was autoloaded or not
```

2020-11-17 01:34 UTC, ElDeveloper commented on qiita_db/study.py
> +        """Sets the title of the study
```suggestion
        """Sets the autoloaded status of the study
```

2020-11-17 01:34 UTC, ElDeveloper commented on qiita_db/study.py
> +            Value to set the autoloaded of this study
```suggestion
            Whether the study was autoloaded
```

2020-11-17 01:46 UTC, antgonza commented
Thank you for review; that's a good question! I don't think we should display it but it will be good to limit functionality for those studies we didn't submit ...

2020-11-17 02:19 UTC, ElDeveloper commented
Yes, I think I was thinking mostly in terms of a meta-analysis to easily check for systematic effects.

2020-11-17 02:19 UTC, merged