2020.11 docs
biocore/qiita pull request #3053
Opened 2020-11-23 14:41 UTC by antgonza

First review/merge https://github.com/biocore/qiita/pull/3048

2020-11-23 19:54 UTC, ElDeveloper requested changes
Just a few minor suggestions/questions. Looks good overall.

2020-11-23 19:54 UTC, ElDeveloper commented on README.rst
> +* Raw data processing for `Target Gene, Metagenomic, Metabolomic and BIOM files <https://qiita.ucsd.edu/static/doc/html/processingdata/index.html#processing-recommendations>`. BIOM files can be added
```suggestion
* Raw data processing for `Target Gene, Metagenomic, Metabolomic and BIOM files <https://qiita.ucsd.edu/static/doc/html/processingdata/index.html#processing-recommendations>`. BIOM files can be added as new preparation files for downstream analyses; however, this cannot be made public.
```

2020-11-23 19:54 UTC, ElDeveloper commented on qiita_pet/support_files/doc/source/faq.rst
> +Metrascriptomic. Check our :doc:`processingdata/processing-recommendations`.
```suggestion
Metatranscriptomic. Check our :doc:`processingdata/processing-recommendations`.
```

2020-11-23 19:54 UTC, ElDeveloper commented on qiita_pet/support_files/doc/source/processingdata/processing-recommendations.rst
> +Note that the selected processing are mainly guided so we can perform meta-analyses,
```suggestion
Note that the selected processing recommendations are mainly guided towards performing meta-analyses,
```

2020-11-23 19:54 UTC, ElDeveloper commented on qiita_pet/support_files/doc/source/processingdata/processing-recommendations.rst
> +bowtie2 alignment step with Woltka classification using either the WoLr1 or Rep200 databases.
What's `WoLr1`?

2020-11-23 19:55 UTC, antgonza commented on qiita_pet/support_files/doc/source/processingdata/processing-recommendations.rst
> +bowtie2 alignment step with Woltka classification using either the WoLr1 or Rep200 databases.
WoLr1 ("Web of Life" release 1)

2020-11-25 00:29 UTC, ElDeveloper approved these changes
Thanks @antgonza

2020-11-25 00:29 UTC, merged